# This is a basic workflow to help you get started with Actions

name: build_and_deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: elliott-and-mycah

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # pushes to a private digital ocean registry
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # install deps
      - name: Install yarn dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      # build project
      - name: Build assets
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Build docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      # Install doctl on the runner
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Push image to DO
        run: |
          doctl registry login
          docker tag $IMAGE_NAME registry.digitalocean.com/mantocko/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME registry.digitalocean.com/mantocko/$IMAGE_NAME:${{ github.sha }}
          docker push registry.digitalocean.com/mantocko/$IMAGE_NAME

      - name: Update kubeconfig
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to DO kubernetes
        uses: Azure/k8s-deploy@v1.3
        with:
          kubectl-version: '1.19.6'
          # letsencrypt-staging may not be necessary unless I want to do more testing
          manifests: |
            k8s/deployment.yml
            k8s/service.yml
            k8s/ingress.yml
            k8s/letsencrypt-prod.yml
            k8s/letsencrypt-staging.yml
          # this does a string replace on the image name with this image tag
          images: |
            registry.digitalocean.com/mantocko/${{ env.IMAGE_NAME }}:${{ github.sha }}
